default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf-8
  host: localhost
  database: currencies_development
  pool: 5
  timeout: 5000
  username: for_currency
  password: "currencies"

test:
  adapter: postgresql
  encoding: utf-8
  host: localhost
  database: currencies_test
  pool: 5
  timeout: 5000
  username: for_currency
  password: "currencies"

production:
  <<: *default
  database: db/production.sqlite3